
services:
  cashflow.payment.api:
    image: ${DOCKER_REGISTRY-}cashflowpaymentapi
    build:
      context: .
      dockerfile: CashFlow.Payment.API/Dockerfile
    networks:
      - backend
    ports:
    - "65231:8080"
    - "65233:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - rabbitmq

  cashflow.reports.api:
    image: ${DOCKER_REGISTRY-}cashflowreportsapi
    build:
      context: .
      dockerfile: CashFlow.Reports.API/Dockerfile
    networks:
      - backend
    ports:
    - "65215:8080"
    - "65222:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPassw0rd
    ports:
      - "1433:1433"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  backend:
    driver: bridge